
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rollout-restart-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rollout-restart-sa
          containers:
          - name: rollout-restart
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment/nginx-rtmp-server
          restartPolicy: OnFailure