
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-restart-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollout-restart-rolebinding
subjects:
- kind: ServiceAccount
  name: rollout-restart-sa
  namespace: default
roleRef:
  kind: Role
  name: rollout-restart-role
  apiGroup: rbac.authorization.k8s.io